name: Build

on:
  push:
    branches: ['**']
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: npm install, and test (ubuntu)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          npm install
          xvfb-run -a npm run test --if-present

      - name: npm install, and test (macos, windows)
        if: ${{ !(matrix.os == 'ubuntu-latest') }}
        run: |
          npm install
          npm run test --if-present
