name: Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install

      - name: Run tests (ubuntu)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: xvfb-run -a npm run test

      - name: Run tests (macos, windows)
        if: ${{ !(matrix.os == 'ubuntu-latest') }}
        run: npm run test
