# Automatically creates a tag when the version in package.json changes.

name: Create Tag

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: butlerlogic/action-autotag@stable
        with:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          strategy: package
          tag_prefix: 'v'
